import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './../globals.css'
import Footer from '@/components/Footer/Footer'
import HomeNavigation from '@/components/Navigation/HomeNavigation'
import { Providers } from './providers'
 import {DM_Sans} from "next/font/google"

 const sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Remake Studio',
  description: 'Generated by create next app',
  icons: "/logo-black.svg`"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en" className={`${sans.className}`}>
      <body className={`px-10 md:px-20   py-8 scroll`}>
        <Providers>
          <HomeNavigation/>
          <main className=' min-h-screen py-10'>
            {children}
          </main>
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
