import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './../globals.css'
import Footer from '@/components/Footer/Footer'
import HomeNavigation from '@/components/Navigation/HomeNavigation'
import { Providers } from './providers'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Remake Studio',
  description: 'Generated by create next app',
  icons: "/logo-black.svg`"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en">
      <body className={`${inter.className} px-24 py-16`}>
        <Providers>
          <HomeNavigation/>
          <main>
            {children}
          </main>
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
