import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './../globals.css'
import Footer from '@/components/Footer/Footer'
import { Providers } from './providers'
 import {DM_Sans} from "next/font/google"
import HomeNavigation from '@/components/Navigation/HomeNavigation/HomeNavigation'
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css';
 const sans = DM_Sans({
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Remake Studio',
  description: 'Generated by create next app',
  icons: "/logo-empty-white.svg"
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  
  return (
    <html lang="en" className={`${sans.className}`}>
      <body className={`px-6 md:px-20 py-8 scroll`}>
        <Providers>
          <ToastContainer 
            position="bottom-left"
            progressStyle={{
              background: "var(--color-accent)"
            }}
            
            autoClose={3000}
            
          />
          <HomeNavigation/>
          <main className=' min-h-screen py-10'>
            {children}
          </main>
          <Footer/>
        </Providers>
        
      </body>
    </html>
  )
}
